USE sucos;

CREATE TABLE TABELA_DE_VENDEDORES (
    MATRICULA INT AUTO_INCREMENT,
    NOME VARCHAR(100),
    PERCENTUAL_COMISSAO DECIMAL(3,2) CHECK (PERCENTUAL_COMISSAO >= 0 AND PERCENTUAL_COMISSAO <= 1.0),
    PRIMARY KEY (MATRICULA)
);

INSERT INTO TABELA_DE_VENDEDORES (
    MATRICULA, NOME, PERCENTUAL_COMISSAO
) VALUES (
    '00235', 'Márcio Almeida Silva', '0.08'
);

INSERT INTO TABELA_DE_VENDEDORES (
    MATRICULA, NOME, PERCENTUAL_COMISSAO
) VALUES (
    '00236', 'Cláudia Morais', '0.08'
);

SELECT * FROM TABELA_DE_VENDEDORES;
