USE sucos;

INSERT INTO TABELA_DE_VENDEDORES (
    MATRICULA, NOME, PERCENTUAL_COMISSAO
) VALUES (
    '00235', 'Márcio Almeida Silva', '0.08'
);

INSERT INTO TABELA_DE_VENDEDORES (
    MATRICULA, NOME, PERCENTUAL_COMISSAO
) VALUES (
    '00236', 'Cláudia Morais', '0.08'
);

SELECT * FROM TABELA_DE_VENDEDORES;
